[policies]
DEFAULTPOLICIES="fileidentification/definitions/default_policies.json"

# string attached to target folder, set absolute to change entirely
[paths]
TMP_DIR="_TMP"
POLICIES_J="_policies.json"
LOG_J="_log.json"
