[project]
name = "fileidentification"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lxml>=5.1.0",
    "requests>=2.31.0",
    "typer>=0.10.0",
    "rich>=13.7.1",
    "beautifulsoup4>=4.13.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
