---

name: Lint Code

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install Python dependencies (uv will install python automatically, if no appropriate version is installed)
        run: uv sync --all-extras --dev
        shell: bash
      - name: Linting with ruff
        run: uv run ruff check . --output-format=github
      - name: Check formatting with ruff
        run: uv run ruff format --check .
      - name: Linting with mypy
        run: uv run mypy .
